### ISSUE TITLE
对中文表名和字段名不支持？

### ISSUE THREAD

**Issue by xixinlove** [liaozb/APIJSON.NET#1]
测试了一下，貌似对中文表名和字段名不支持。需要修改StringExtensions和IdentityService？
PS：虽然中文表名和字段名本身是个奇葩，但是考虑到有太多神仙随心所欲的起名，还是兼容下比较好。

**Comment by liaozb** [comment]
去掉正则验证了 改用缓存表结构 然后验证表名和字段正确
