### ISSUE TITLE
如何实现head方法？

### ISSUE THREAD

**Issue by 390620652** [liaozb/APIJSON.NET#33]
HEAD:
普通获取数量，
可用浏览器调试

base_url/head/

这部分功能没有

**Comment by TommyLemon** [comment]
POST /head
```js
{
  "User": {
     "@column": "name"
  }
}
```

可以用 GET 替代

POST /get
```js
{
  "User": {
     "@column": "count(name)" // 没有传有效 @column 则直接默认 count(*)
  }
}
```

https://github.com/Tencent/APIJSON/blob/master/Document.md#3.1

**Comment by 390620652** [comment]
`{
  "User": {
     "@column": "count(name)" // 没有传有效 @column 则直接默认 count(*)
  }
}`
这样写好像没有用，会报错，说没有count(name)、count(1)或count(*)这列

**Comment by TommyLemon** [comment]
那应该是 .NET 版没有支持 SQL 函数导致的，可以改下对应源码来支持下
