### ISSUE TITLE
权限配置

### ISSUE THREAD

**Issue by wanghaisheng** [liaozb/APIJSON.NET#7]
![](https://raw.githubusercontent.com/liaozb/APIJSON.NET/master/APIJSON.NET/1.png)
请问您这边示范的可配置字段
"*"应该是全部字段 如果某些字段不允许怎么配置呢

**Comment by liaozb** [comment]
不允许就填允许的字段 - -！

**Comment by wanghaisheng** [comment]
谢谢  我尝试枚举一下

**Comment by wanghaisheng** [comment]
图片里查询、修改、添加、删除能罗列一下分别对应官方文档里哪几种方法嘛  get gets head put等等

**Comment by liaozb** [comment]
增删改查都是post 请求 ，也是可以进去改  JsonController.cs 文件里
